### ISSUE TITLE
Type hints & PEP 561 packaging

### ISSUE THREAD

**Issue by tuukkamustonen** [madzak/python-json-logger#118]
Add type hints to all (public API) code make the distribution PEP 561 compliant. This allows `mypy` (and other tools?) to find the type hints and use them in linting.

In practice, add `py.typed` file to `src/pythonjsonlogger`, and include it in the package:

```py
setup(
    package_data={'pythonjsonlogger': ['py.typed']},
    zip_safe=False,  # not needed with wheels, AFAIK
)
```

PEP 561: https://www.python.org/dev/peps/pep-0561/

**Comment by bringhurst** [comment]
I'm having trouble figuring out what should be done in this case:

```
      def format(self, record):
          """Formats a log record and serializes to json"""
          message_dict = {}
          if isinstance(record.msg, dict):
              message_dict = record.msg
              record.message = None
          else:
              record.message = record.getMessage()
```

with a related test:

```
    def testJsonCustomDefault(self):
        def custom(o):
            return "very custom"
        fr = jsonlogger.JsonFormatter(json_default=custom)
        self.logHandler.setFormatter(fr)

        msg = {"adate": datetime.datetime(1999, 12, 31, 23, 59),
               "normal": "value"}
        self.logger.info(msg)
        logJson = json.loads(self.buffer.getvalue())
        self.assertEqual(logJson.get("adate"), "very custom")
        self.assertEqual(logJson.get("normal"), "value")
```

Note that record.msg is type of Dict, but logging.LogRecord.msg in typeshed is type of str.

I'll think about it a bit and see what I can do, but any help would be appreciated.

**Comment by alexmirrington** [comment]
Any additional progress on this? Do we have a list of what needs to be completed in order to achieve PEP 561 compliance?

**Comment by mwgamble** [comment]
There's already a `py.typed` file in the repo, but it doesn't seem to be included in the packages uploaded to PyPI.

**Comment by akshayphdk** [comment]
@madzak perhaps https://github.com/madzak/python-json-logger/pull/156 would bring this issue closer to done?

**Comment by Eyal-Shalev** [comment]
@madzak any updates on this?
