### ISSUE TITLE
No StackTrace info on the log

### ISSUE THREAD

**Issue by hitokiri82** [madzak/python-json-logger#12]
Hello. 

I'm trying to use this module to format django's log. The problem I'm having is that the full message of the stack trace when there's an exception, including the actual Exception name and message, is not showing up in my log files. 

Any idea for how I might fix this?

**Comment by sullivanmatt** [comment]
I have opened a PR to address this issue: https://github.com/madzak/python-json-logger/pull/26

**Comment by madzak** [comment]
Fix is in Pypi.
