### ISSUE TITLE
any tool to visualize the log

### ISSUE THREAD

**Issue by sunset1234321** [madzak/python-json-logger#125]
seems only cloud provider (datadog, google log, etc) provides a nice interface for interacting with the json log)

is there any tool on local that supports those visualizations and interaction?

**Comment by chandruxp** [comment]
> seems only cloud provider (datadog, google log, etc) provides a nice interface for interacting with the json log)
> 
> is there any tool on local that supports those visualizations and interaction?

You can use ELK kibana ?
