### ISSUE TITLE
How can I output the json with newlines?

### ISSUE THREAD

**Issue by pmcl77** [madzak/python-json-logger#126]
Im simply setting up the jsonformatter with:

`streamformat = jsonlogger.JsonFormatter("%(asctime)s %(levelname)s %(levelno)s %(module)s %(message)s %(lineno)s ")`

It will output the json all in one line. Is there an option to have a "pretty" output somehow like you showed in your example output?

**Comment by damobrisbane** [comment]
Unfortunately the _jq_ trick didnt seem to work for me, when debugging in cli, stack traces put invalid json on stdout. However setting indent on the constructor seems to work fine:

'''
  formatter = jsonlogger.JsonFormatter(json_indent=2)
'''

See [Allows pretty printing of JSON messages w/ cls kwarg #45](https://github.com/madzak/python-json-logger/pull/45)
