### ISSUE TITLE
v2.0.3 breaks with percentage style log format

### ISSUE THREAD

**Issue by aberres** [madzak/python-json-logger#144]
A MR says it all, right? :) https://github.com/madzak/python-json-logger/pull/143

Since 0055dc5b273949ee7432665eeddbe37781d9dc01 things go south when a configured log field is not followed by an `s`.

**Comment by madzak** [comment]
cut v2.0.4 with your fix. thanks again!

**Comment by aberres** [comment]
Great, thanks for the quick response.
