### ISSUE TITLE
Broken link in README.MD

### ISSUE THREAD

**Issue by muenchenscott** [madzak/python-json-logger#152]
[Wesley Tanaka - Structured log files in Python using python-json-logger](https://wtanaka.com/node/8201)
Link appears to be unavailable.

**Comment by MaxPowerWasTaken** [comment]
also just came across this library and tried this link - dead for me today too...

```
This Serverless Function has crashed.

Your connection is working correctly.

Vercel is working correctly.

500: INTERNAL_SERVER_ERROR
Code: FUNCTION_INVOCATION_FAILED
ID: cle1::ft59v-1668057776000-cfdbc13f57b5
```

**Comment by MaxPowerWasTaken** [comment]
appears this is a duplicate issue of https://github.com/madzak/python-json-logger/issues/137

**Comment by madzak** [comment]
Updated link
