### ISSUE TITLE
Drop support of old python versions

### ISSUE THREAD

**Issue by lopagela** [madzak/python-json-logger#153]
While browsing the code, I realized that some code is written with `python2` in mind (especially the test).
`python2` is not supported since January 2020 (https://www.python.org/doc/sunset-python-2/).

I'd also suggest changing the packaging of this library to drop the support of `python3.5` (EOL 2020-09-13) and `python3.6` (EOL 2021-12-23) (source: https://endoflife.date/python)

Some guidance can be found here: https://packaging.python.org/en/latest/guides/dropping-older-python-versions/

**Comment by louis-jaris** [comment]
This issue can be closed, the PR was merged
