### ISSUE TITLE
Version 2.0.5 is backward-incompatible

### ISSUE THREAD

**Issue by afallou** [madzak/python-json-logger#163]
In version `2.0.5`, a new positional argument was added to `merge_record_extra` (see https://github.com/madzak/python-json-logger/pull/148/files#diff-f8bb65b90b766ff126c6a5f48bdbf006cb11bfd2f973d75c04b7c4985ebddf60R28), which is a breaking change. It seems like this argument should an optional keyword argument instead.

If you agree, I can try to get a PR up.

**Comment by madzak** [comment]
Yes please
