### ISSUE TITLE
Package project as Python wheel

### ISSUE THREAD

**Issue by svisser** [madzak/python-json-logger#17]
In addition to the source package, there is a new standard for packaging projects. As this is a pure Python project, it should be a matter of following the instructions on http://pythonwheels.com. This should make the installation faster (plus other benefits, see site).

**Comment by madzak** [comment]
Added it.

**Comment by beanaroo** [comment]
Thanks! Unfortunately, there does not appear to be a published wheel for the latest version (2.0.1)
