### ISSUE TITLE
How to append logs in the current dict ?

### ISSUE THREAD

**Issue by rreubenur** [madzak/python-json-logger#25]
Thanks for the nice library ! I tried your example which is given in the readme section.  It's working fine.

My problem is I am using `logging.FileHandler('reuben.json')` to write the dump in a file. What happening is every time a log message is entering as a separate entry instead of an item of a list or dictionary.

Is it possible to create the json in the given below format :

```
log.error({"host": "host1", "message": "Failed to install"})
log.info({"host": "host2", "message": "successfully installed"})
```

json : 

```
[{"host": "host1", "message": "Failed to install"}, {"host": "host2", "message": "successfully installed"}]
```

**Comment by madzak** [comment]
LogRecord is only the log message, not the log. To do this I would probably have to create a new logger object. I'll look into it.

**Comment by svisser** [comment]
Is there a particular use case for that? It seems better to think of logging calls as separate calls that each write one line of JSON to the file. You'd then process the file as such: it's not a JSON file but a file with lines of JSON.

**Comment by madzak** [comment]
rreubenur's use case makes sense, he's trying to make his log file a true JSON file. If we did this, you wouldn't have to use the Logger override class and could continue to use just the formatter. I guess i think of it more as an add-on not a replacement for the formatter.

**Comment by little-dude** [comment]
fwiw, I came up with the following function to convert the log files into valid json :

```python
def make_valid_json_file(file_path):
    # Taken from :
    # http://stackoverflow.com/questions/39086/search-and-replace-a-line-in-a-file-in-python
    # Create temp file
    fh, abs_path = mkstemp()
    # Write temp file line by line
    with open(abs_path, 'w') as new_file:
        with open(file_path) as old_file:
            prev_line = "["
            for line in old_file:
                new_file.write(prev_line.replace('\n', ',\n'))
                prev_line = line
            new_file.write(prev_line.replace('\n', ']'))
    close(fh)
    # Remove original file
    remove(file_path)
    # Move new file
    move(abs_path, file_path)
```
