### ISSUE TITLE
Change json output - arrays instead of hashes

### ISSUE THREAD

**Issue by PWojtal** [madzak/python-json-logger#33]
Hello,
I want to show output from logger as data table at webpage. To do this I need to have output in slightly different format - instead of hashes I need to have array of arrays, like described here: https://datatables.net/examples/ajax/simple.html
How could I change log format in the easiest way?

**Comment by Rouji** [comment]
FYI you can also use hashes with datatables
https://datatables.net/reference/option/columns.data#Examples
