### ISSUE TITLE
more verbose defaults for JsonFromatter

### ISSUE THREAD

**Issue by kevhill** [madzak/python-json-logger#35]
it looks like the default format is just `'%(message)s'`. It certainly works, but provides no additional info for log parsers to use.

In order for someone to get the maximum benefit with the minimum effort from this package, I'd suggest changing the default format to something a bit more verbose, like `'%(message)s %(levelname)s %(funcName)s %(name)s %(pathname)s'`

**Comment by tuukkamustonen** [comment]
I don't know how much benefit this would be. It now uses the default from `logging.Formatter` and you can override it in your logging configuration and via constructor. I kinda like it - people's needs will differ anyway, so it's safe choice to use the underlying default.

**Comment by madzak** [comment]
As @tuukkamustonen I used the default from <code>logging.Formatter</code> to keep in the "spirit" of the logging module. I imagined overriding to provide those custom message formats.
