### ISSUE TITLE
Add program name and severity in prefix

### ISSUE THREAD

**Issue by unixsurfer** [madzak/python-json-logger#46]
Hi,

I want to send JSON logging to rsyslogd over UDP and configure rsyslogd to write those in a file.
The only way I can do that in rsyslogd is to configure it to look at the program name with the following
snippet in rsyslsog.d:

```
if $programname startswith 'anycast-healthchecker' then /var/log/anyacast-healthchecker.log
&~

```
and set prefix to `anycast-healthchecker`. But, the logs don't arrive in the file as rsyslog expects to see first the severity (levelname in python) and then the program name. If I set prefix to info `anycast-healthchecker` then rsyslogd is able to match the program name and route the log to the file.

levelname is dynamic therefore I can't use the prefix in the away I mentioned, thus I would like to be added automatically based on the severity of the logged message.

Any ideas how I can achieve this?
Thanks,
Pavlos

**Comment by madzak** [comment]
Sorry! I'm way late to the party but I'm not sure how to accomplish that off the top of my head. If you still need this, reopen and we'll hash it out.
