### ISSUE TITLE
Missing Git tag for 0.1.7 release

### ISSUE THREAD

**Issue by felixonmars** [madzak/python-json-logger#47]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by peterclearmetal** [comment]
For reference 0.1.7 is [1a4647](https://github.com/madzak/python-json-logger/commit/1a464798a033d3f8034c05811dbdf097ec4b0201).

**Comment by madzak** [comment]
updated 0.1.7 and 0.1.6 tags
