### ISSUE TITLE
Allow milliseconds in asctime

### ISSUE THREAD

**Issue by malcojosh** [madzak/python-json-logger#54]
https://stackoverflow.com/questions/6290739/python-logging-use-milliseconds-in-time-format/6290946#6290946 outlines how to add millisecond resolution on log files, but I'm having trouble figuring out how to add it to pythonjsonlogger. 

EDIT: Just realized that milliseconds are included by default if datefmt is _not_ specified. Apologies. Thank you for this library.

**Comment by WillJCJ** [comment]
This seems to be working now.

Dictionary logging config:
```
    ...
    "formatters": {
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "fmt": (
                "%(asctime)s %(message)s"
            ),
            "datefmt": "%Y-%m-%dT%H:%M:%S.%s%z",
        },
    },
    ...
```
Gives me:
```
{
    "asctime": "2018-06-14T15:12:00.1528985520+0100",
    "message": "Hello, World!"
}
```

Not sure how to format it to 3 decimal places if nanoseconds aren't your thing.
