### ISSUE TITLE
Add possibility to provide ensure_ascii parameter to json.dumps.

### ISSUE THREAD

**Issue by Savier** [madzak/python-json-logger#62]
Utf-8 is rather common now, and i'd like to see my national messages readable after formatting. Now it looks like that:
```
In [20]: log.debug('Привет')
{"message": "\u041f\u0440\u0438\u0432\u0435\u0442"}
```
But I want it as
```
In [20]: log.debug('Привет')
{"message": "Привет"}
```
[PR#63](https://github.com/madzak/python-json-logger/pull/63)

**Comment by Savier** [comment]
Thank you for acceptance. I saw you have merged pack of changes. It would be nice to release it to pypi!

**Comment by kishibashi3** [comment]
Hi!
I want to use your pythonjsonlogger with utf-8 too.
please tell me when you plan to release this issue.

**Comment by kini** [comment]
This is already available in the latest released version. This issue should be closed.
