### ISSUE TITLE
Doesn't respect `format` keyword

### ISSUE THREAD

**Issue by akkartik** [madzak/python-json-logger#70]
Say I define a logging config like this:

```logging-config.yaml
version: 1

formatters:

  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(name)s %(levelname)s [%(filename)s:%(lineno)s] %(message)s"

handlers:

  console:
    class: logging.StreamHandler
    level: INFO
    formatter: json
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [ console ]
```

The resulting JSON includes no field that shows the log line in the `format` specified, including the `filename` and line number (`lineno`) before each message. Instead, it seems to *parse* the format string to determine that it needs to include the `filename` and `lineno` attributes in each log line.

This seems to be a deliberate design decision since it's present in [the very first commit of the project](https://github.com/madzak/python-json-logger/commit/94ec88caa159d19eb647e32113f0f4032db65e3f#diff-c05cf3dbb68948c991a8fe8fb9ac82f0) (the `formatterParse` variable). I'm curious why you overloaded the `format` parameter in this way to specify what the JSON should include, and why you override the `format` parameter to never actually be used as it is meant to. (I'd be happy to contribute an update to the Readme once I understand your rationale.)

**Comment by xmo-odoo** [comment]
> I'm curious why you overloaded the format parameter in this way to specify what the JSON should include

I assume it's because the intent was to be able to drop python-json-logger into an existing project and get all the information which was previously available, as JSON rather than a formatted string.

The formatted string is not actually useful since you have all the information in a more structured format as part of your json log record, but if you actually want it it's pretty trivial: override `add_fields` and assign `self.formatMessage(record)` to whatever key you want on the `log_record` dict.

**Comment by haizaar** [comment]
> and why you override the format parameter to never actually be used as it is meant to.

I'm not related to author - just happen to use this project. The method of parsing format string may look quite hacking but IMHO a neat way to enable drop-in replacement with other (stdlib) loggers. Indeed having json with broken-down fileds as per format string is of a value to me.

Btw, if you use `{}` style for formatting, you'll need to to patch `JsonFormatter` class: https://github.com/madzak/python-json-logger/issues/74
