### ISSUE TITLE
Only "%" style is supported

### ISSUE THREAD

**Issue by haizaar** [madzak/python-json-logger#74]
Since Python 3.2, formatters support new "{" and "${" [styles](https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles), however JsonFormatter's parse method explicitly [expects](https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py#L147) "%" notation. 

This results in empty message is e.g. `{message}` used as logger formatting string.

**Comment by haizaar** [comment]
For "{" style you can do:
```python
     def parse(self):
        field_spec = string.Formatter().parse(self._fmt)
        return [s[1] for s in field_spec]
```

**Comment by xmo-odoo** [comment]
An alternative method which should work is to "render" the format string using a custom Mapping object which records which key was accessed (and returns garbage):

* using `str.format_map` for `{`
* using `Template.substitute` for `${` (it can take a positional mapping)
* using the normal `%` for `%`

```python
import string

class A:
    def __init__(self):
        self.fields = set()
    def __getitem__(self, key):
        self.fields.add(key)
        return ''

for render in [
        lambda o: '%(foo)s %(bar)s' % o,
        '{foo} {bar}'.format_map,
        string.Template("$foo $bar").substitute,
]:
    obj = A()
    render(obj)
    print(obj.fields)
```
yields the relevant keys for all three methods. The one issue would be that this method would behave "strictly" for the `%` case, and cases like #86 (invalid format strings which happen to be understood by json-logger) would be completely broken. So maybe this should only be used for `{` and `${` formats.
