### ISSUE TITLE
Unreleased version on PyPI?

### ISSUE THREAD

**Issue by Dunedan** [madzak/python-json-logger#76]
PyPI currently offers `python-json-logger==0.1.11` (https://pypi.org/project/python-json-logger/), but the latest version available in this repository is `0.1.10`. Also there is no changelog for such a version, neither here nor on PyPI. So what's the matter with `0.1.11`? While I don't believe that it's the case, one could believe that the package currently available through PyPI is a compromised one.

**Comment by madzak** [comment]
Thanks for the concern, v0.1.11 is the latest (the version was updated in a merged commit). I’ll add some change log/version tag in the next week (traveling currently).
