### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by PabloCastellano** [madzak/python-json-logger#90]
Hello @madzak. 

The readme says:

> NOTICE: Python2.7 is only supported up to v0.1.11. The next release, v2.0, will support Python3 only

Python 2 is unsupported since 1st Jan 2020. Is there any roadmap for 2.0 or could you just make a new release supporting only Python3?

Thanks!

**Comment by radzak** [comment]
Hey @madzak.

Can you let us know if you're gonna continue maintaining this package? There hasn't been any activity recently, hence I'm wondering.

Thanks!

**Comment by madzak** [comment]
Hi, thanks @radzak for reaching out on so many mediums. I've merged all PRs and cut the 2.0 release to Github and PyPi. I'll process the open issues later but sorry again for the silence this year.

**Comment by radzak** [comment]
@madzak awesome! thanks a lot
