### ISSUE TITLE
ORJSON

### ISSUE THREAD

**Issue by rspadim** [madzak/python-json-logger#93]
How to use orjson instead standard json library?
What about doing this at logging config?

**Comment by liampauling** [comment]
You can already choose your own encoder/serializer:

https://github.com/madzak/python-json-logger#adding-custom-object-serialization

**Comment by alexsavio** [comment]
The problem is that `orjson.dumps` does not have the same keyword arguments as the ones being used here: https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py#L192
it only accepts `default` and `option` as explained here: https://github.com/ijl/orjson#serialize
