### ISSUE TITLE
Type Annotations

### ISSUE THREAD

**Issue by MartinThoma** [madzak/python-json-logger#95]
I'm currently annotating a code base and wonder what the types of [`add_fields(self, log_record, record, message_dict)`](https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py#L146) are. My current best guess:

```python
from typing import Any, Dict
import logging

def add_fields(self, log_record, record:logging.LogRecord, message_dict: Dict[str, Any]) -> None: ...
```

What is `log_record`? Maybe a `Dict`?

On a more general note: What do you think about adding type annotations? As you [still support Python 3.4 and 3.5](https://github.com/madzak/python-json-logger/blob/master/setup.py#L24), they should be added as type stubs. If you want, I can help you get started :-)

**Comment by the-wondersmith** [comment]
I'll happily pitch in, if any help is needed on this.

@MartinThoma you should be able to get the types by doing something like:

```python
def add_fields(self, *args, **kwargs):
    for pos, arg in enumerate(args):
        print(f"Arg {pos}:\t{type(arg)} -> {arg}"
    for kw, arg in kwargs.items():
        print(f"Kwarg {kw}:\t{type(arg)} -> {arg}") 
```

Add the rest of the `add_fields` method then of course just fire up a logging instance and log something. It'll probably be messy in the console, but it should also tell you what you'd like to know.

**Comment by MartinThoma** [comment]
Thank you for the support. I no longer have access to that code, so I cannot tell what the solution was/is.
